name: tappyfi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.1.2
  shared_preferences: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
